#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
LOGGER="logger -t [NPC]"

npc_Path="$(command -v npc)"

start_service() {
	if [ -f /usr/local/bin/npc ] ; then
		${LOGGER} "Moving npc to /usr/bin ..."
		mv -f /usr/local/bin/npc /usr/bin/npc
	fi
	if [ -f /usr/local/bin/npc-update ] ; then
		${LOGGER} "Moving npc-update to /usr/bin ..."
		mv -f /usr/local/bin/npc-update /usr/bin/npc-update
	fi
	local basic_list="enable server_addr protocol vkey dns"
	for i in $(echo $basic_list);do
		local eval $i="$(uci_get_by_type npc 0 $i)"
	done;unset i


	if [ "$enable" = 1 ]
	then
		${LOGGER} "Starting NPS Client(NPC) ..."
		procd_open_instance
		procd_set_param command $npc_Path -server=${server_addr} -vkey=${vkey} -type=${protocol} -dns_server=${dns} -log=off
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	else
		${LOGGER} "NPS Client(NPC) Service is now disabled ..."
	fi
}

stop_service() {
	$LOGGER "Stopping NPS Client(NPC) ..."
}

service_triggers() {
	procd_add_reload_trigger "npc"
}

uci_get_by_type() {
	local ret=$(uci get npc.@$1[$2].$3 2>/dev/null)
	echo ${ret:=$4}
}
