# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
# Copyright (C) 2024-2025 Duan <duan@d-jy.net>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NPS
LUCI_DEPENDS:=+nps
LUCI_PKGARCH:=all
PKG_VERSION:=1.7
PKG_RELEASE:=3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
